name: India Pincode Finder
description: Find any Pincode or Post Office in India. Free, fast, and ad-free tool in Odia and English.
# If your repo is named "pincode-finder", uncomment the line below:
# baseurl: "/pincode-finder"
